# Generated by Django 5.2.8 on 2025-11-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='buy_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='stock_symbol',
            field=models.CharField(max_length=20),
        ),
    ]
